sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - CS_CHECK=true

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source --no-scripts

script:
  - composer test
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

notifications:
  email: true