version: '2'

volumes:
  # MySQL Data
  api-mysql-data:
    driver: local

services:
  mysql:
    image: ambientum/mysql:5.7
    container_name: com-mysql
    volumes:
      - api-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=lumen_api
      - MYSQL_DATABASE=lumen_api
      - MYSQL_USER=lumen_api
      - MYSQL_PASSWORD=lumen_api

  php:
    build: ./devops/docker/php/
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    links:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - 8082:80
    volumes:
      - ./devops/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php